#!/bin/bash

# Load your key and start the backend
#export OPENAI_API_KEY=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
export ANTHROPIC_API_KEY=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
uv run python hello.py
